name = "wrangler-basic"

# Fetch handler is defined here
main = "src/index.ts"

compatibility_date = "2022-11-11"

# otel config
compatibility_flags = [ "nodejs_compat" ]
rules = [
  { type = "CommonJS", globs = ["**/*.js"], fallthrough = true },
  { type = "ESModule", globs = ["**/*.js"], fallthrough = true },
]
# [build.esbuild]
# bundle = { external = ["", "module2"] }

[vars]
OTEL_SERVICE_NAME=""
OTEL_COLLECTOR_URL=""
OTEL_COLLECTOR_API_KEY=""

# Scheduled Handlers:
[triggers]
# protip: crontab.guru
# “At 00:00 on every 3rd day-of-month.”
crons = [ "* * 3 * *" ]

# Queue Handlers
[[queues.consumers]]
  queue = "my-queue"
  max_batch_size = 10
  max_batch_timeout = 30
  max_retries = 10
  dead_letter_queue = "my-queue-dlq"
